server:
  port: 8082
  servlet:
    context-path: '/ead-authuser/'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ead-authuser-v2
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show-sql: true
  output:
    ansi:
      enabled: Always
  application:
    name: ead-authuser-service
  rabbitmq:
    addresses: amqps://pbnubozr:xM3lGCUyQzjF_kfiTtyGBRbHJgDa_W8N@jackal.rmq.cloudamqp.com/pbnubozr


logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      user-event: ead.userevent

resilience4j:
  retry:
    instances:
      default-retry-instance:
        maxRetryAttempts: 3
        waitDuration: 5s
  circuitbreaker:
    instances:
      default-circuitbreaker-instance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80



