server:
  port: ${PORT}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CarlosLaurine/Property-Files-Repo-for-Config-Server-E-LearningPlatform-With-Microsevices-Architecture
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}

encrypt:
  key: 8y/B?E(H+MbQeShVmYq3t6w9z$C&F)J@NcRfUjWnZr4u7x!A%D*G-KaPdSgVkYp2

ead:
  configServer:
    username: ${CONFIG_SERVER_USERNAME}
    password: ${CONFIG_SERVER_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80


