server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CarlosLaurine/Property-Files-Repo-for-Config-Server-E-LearningPlatform-With-Microsevices-Architecture
          default-label: main

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost


