server:
  port: 8888

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/CarlosLaurine/Property-Files-Repo-for-Config-Server-E-LearningPlatform-With-Microsevices-Architecture
          default-label: main

ead:
  service-registry:
    username: serviceregistryclient
    password: 'secretead123sr'
  config-server:
    username: configServerClient
    password: 'secretead123cs'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.service-registry.username}:${ead.service-registry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost


